# Run this executable to install all python libraries required for HetKit

echo Thanks for using HetKit. Required Python3 libraries are now being installed.
echo Installing pyqt5...
python3 -m pip install --user PyQt5 | grep -m 1 -o "abc" | grep -o "123"
echo Installing numpy...
python3 -m pip install --user numpy | grep -m 1 -o "abc" | grep -o "123"
echo Installing matplotlib...
python3 -m pip install --user matplotlib | grep -m 1 -o "abc" | grep -o "123"
echo Installing SciPy...
python3 -m pip install --user scipy | grep -m 1 -o "abc" | grep -o "123"
echo Installing imutils...
python3 -m pip install --user imutils | grep -m 1 -o "abc" | grep -o "123"
echo Installing pillow...
python3 -m pip install --user pillow | grep -m 1 -o "abc" | grep -o "123"
echo Installing gstools...
python3 -m pip install --user gstools | grep -m 1 -o "abc" | grep -o "123"
echo Installing Pandas...
python3 -m pip install --user pandas | grep -m 1 -o "abc" | grep -o "123"
echo Installing Datetime...
python3 -m pip install --user datetime | grep -m 1 -o "abc" | grep -o "123"
echo Installing Sklearn...
python3 -m pip install --user scikit-learn | grep -m 1 -o "abc" | grep -o "123"
echo All required Python3 libraries have been installed.
